version: '3.6'
services:
    web:
      image: nginx
      container_name: my_mysql
      ports:
        - 80:80
      volumes:
        - ./my_data/:/usr/share/nginx/html
      networks:
        - Anet
    
    web1:    
      image: httpd
      container_name: httpt
      volumes:
         - ./my_backup/:/var/www/html
      networks:
         - Anet

networks:
 Anet:
